version: "3.9"

services:
  bot: 
    build:
      context: ./
      dockerfile: Dockerfile
    command: python main.py
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - .:/home/bot
    depends_on: 
      - redis
  redis: 
    image: redis/redis-stack-server:latest
    volumes:
      - redis_local:/data

volumes:
  redis_local: